# Instruct the Intel P-state scaling driver to use balance_power Energy Performance Preference (EPP)
# This forces the kernel to bin interrupts and tasks to the LP E-Cores on the SoC tile,
# leaving P-cores fully offline until sustained, raw computational power is requested.
w /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference - - - - balance_power