# Core Ultra mTHP configuration optimized for Intel Redwood Cove & Crestmont boundaries
w /sys/kernel/mm/transparent_hugepage/hugepages-64kB/enabled - - - - always
w /sys/kernel/mm/transparent_hugepage/hugepages-2048kB/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise
