# Core Ultra mTHP configuration safely enabling performance alignments
w /sys/kernel/mm/transparent_hugepage/hugepages-16kB/enabled - - - - always
w /sys/kernel/mm/transparent_hugepage/hugepages-32kB/enabled - - - - always
w /sys/kernel/mm/transparent_hugepage/hugepages-64kB/enabled - - - - always
w /sys/kernel/mm/transparent_hugepage/hugepages-128kB/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/hugepages-256kB/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise