# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-silverblue-bluebuild
description: Core Ultra Dynamic HW-Optimized System Engine.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    install:
      packages:
        - intel-media-driver
        - libva-utils
        - gstreamer1-vaapi
        - intel-gpu-tools
        - fastfetch
        - intel-lpmd
        - thermald
        - intel-npu-driver
        - onevpl-intel-gpu
        - intel-opencl
        - powertop
      skip-unavailable: true
      skip-broken: true
      allow-erasing: true
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-tour
        - yelp
        - gnome-user-docs
        - rygel
  - type: kargs - module_blacklist=i915 - cpuidle.governor=teo - 
      rcutree.enable_rcu_lazy=1 - acpi.ec_no_wakeup=1
    kargs:
      - nmi_watchdog=0
      - nowatchdog
      - rcutree.rcu_idle_gp_delay=4
      - intel_pstate=active
      - split_lock_detect=off
      - quiet
      - splash
      - workqueue.power_efficient=y
      - pcie_aspm=auto
      - iommu=pt
      - intel_iommu=on
      - page_alloc.shuffle=1
      - intel_idle.max_cstate=10
      # Multi-architecture Core Ultra i915 blacklist block (MTL, ARL, and LNL)
      # Multi-architecture Core Ultra xe force-probe block (MTL, ARL, and LNL)
      - xe.force_probe=7d55,7dd5,7d51,7d67,7d41,e20b,e20d,e202
      # Allow NVMe controller to drop into PS4 deep sleep (under 5.5ms wake latency)
      - nvme_core.default_ps_max_latency_us=5500
  - type: systemd
    system:
      masked:
        - intel-lpmd.service
        - irqbalance.service
      enabled:
        - thermald.service
        - disable-usb-wakeups.service
        - flatpak-automatic-upgrade.timer
        - powertop.service
        - cpupower-powersave.service
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.brave.Browser
          - com.mattjakeman.ExtensionManager
          - org.freedesktop.Platform.VAAPI.Intel
  - type: signing
