vm.page-cluster = 0
vm.max_map_count = 1048576
vm.watermark_scale_factor = 10
vm.dirty_background_ratio = 10
vm.dirty_ratio = 30
vm.dirty_writeback_centisecs = 1500
vm.dirty_expire_centisecs = 3000
vm.compaction_proactiveness = 20
vm.laptop_mode = 5
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
kernel.yama.ptrace_scope = 1
