# Move memory pages to the highly compressed ZRAM early to keep physical RAM completely unfragmented
vm.swappiness = 180

# Keep watermark boost factor off to prevent random kswapd wakeups
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0

# Limit NVMe SSD active write cycles by holding dirty data in cache longer
vm.dirty_writeback_centisecs = 1500
vm.dirty_expire_centisecs = 1500
vm.dirty_background_ratio = 5
vm.dirty_ratio = 20

# Network latency optimizations
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr