monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" },
      { node.name = "~alsa_input.*" }
    ]
    actions = {
      update-props = {
        api.alsa.period-size = 2048
        api.alsa.headroom    = 2048
        session.suspend-timeout-seconds = 1
      }
    }
  }
]
