[zram0]
# Allocate the logical equivalent of physical RAM size as ZRAM
zram-size = ram
# High-efficiency, low-latency compression algorithm
compression-algorithm = zstd
# Enforce highest execution priority over any generic block storage
swap-priority = 100